more robust safety check for commits to main

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,10 @@
+#!/usr/bin/env sh
+
+# Prevent commits to main branch
+current_branch=$(git branch | grep '*' | cut -d ' ' -f 2)
+if [ "$current_branch" = 'main' ]; then
+  printf '\033[1;31mCommit aborted.\033[m Please switch to a feature branch.\n'
+  exit 1
+fi
+
 pnpm lint
-pnpm check-main-branch
